spring.datasource.url=jdbc:postgresql://dpg-d4t1j17pm1nc73889r1g-a.frankfurt-postgres.render.com:5432/club_db_3fbt
spring.datasource.username=club_user
spring.datasource.password=5n0XkyCMDbOC650PlPytOIYr91bnFzIi

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
